/*
 * File: app/store/CakesStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coffeeshop.store.CakesStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Coffeeshop.model.Product',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    config: {
        data: [
            {
                name: 'Chocolate Cake',
                image: 'cakes/chococake.jpg',
                id: 'K-CHOC',
                category: 'CAKE'
            },
            {
                name: 'Carrot Cake',
                image: 'cakes/carrotcake.jpg',
                id: 'K-CARR',
                category: 'CAKE'
            },
            {
                name: 'Special Cake!',
                image: 'cakes/specialCake.jpg',
                id: 'K-SPEC',
                category: 'CAKE'
            },
            {
                name: 'Cookies',
                image: 'cakes/cookies.jpg',
                id: 'K-COOK',
                category: 'CAKE'
            },
            {
                name: 'Cupcakes',
                image: 'cakes/cupcake.jpg',
                id: 'K-CUP',
                category: 'CAKE'
            },
            {
                name: 'Blueberry Muffin',
                image: 'cakes/blueberrymuffin.jpg',
                id: 'K-BLMU',
                category: 'CAKE'
            }
        ],
        model: 'Coffeeshop.model.Product',
        storeId: 'CakesStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});