/*
 * File: app/store/CoffeeStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coffeeshop.store.CoffeeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Coffeeshop.model.Product',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    config: {
        data: [
            {
                name: 'Cappuccino',
                image: 'coffee/cappuccino.jpg',
                id: 'C-CAPP',
                category: 'COFFEE'
            },
            {
                name: 'Coffee Special',
                image: 'coffee/coffeeSpecial.jpg',
                id: 'C-COSP',
                category: 'COFFEE'
            },
            {
                name: 'Hot Chocolate',
                image: 'coffee/hotchocolate.jpg',
                id: 'C-HOCH',
                category: 'COFFEE'
            },
            {
                name: 'Latte Machiato',
                image: 'coffee/lattemachiato.jpg',
                id: 'C-LAMA',
                category: 'COFFEE'
            },
            {
                name: 'Espresso',
                image: 'coffee/espresso.jpg',
                id: 'C-ESPR',
                category: 'COFFEE'
            },
            {
                name: 'Tea',
                image: 'coffee/tea.jpg',
                id: 'C-TEA',
                category: 'COFFEE'
            }
        ],
        model: 'Coffeeshop.model.Product',
        storeId: 'CoffeeStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});