/*
 * File: app/store/OrderStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coffeeshop.store.OrderStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Coffeeshop.model.Product',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    config: {
        groupField: 'category',
        model: 'Coffeeshop.model.Product',
        storeId: 'OrderStore',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'array'
            }
        }
    }
});