/*
 * File: app/view/OrderContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coffeeshop.view.OrderContainer', {
    extend: 'Ext.Container',
    alias: 'widget.ordercontainer',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 60,
                title: 'Order',
                items: [
                    {
                        xtype: 'button',
                        docked: 'right',
                        itemId: 'checkoutButton',
                        ui: 'confirm',
                        width: 100,
                        text: 'Checkout'
                    },
                    {
                        xtype: 'button',
                        itemId: 'logout',
                        ui: 'back',
                        text: 'Logout'
                    }
                ]
            },
            {
                xtype: 'list',
                itemId: 'orderlist',
                deferEmptyText: false,
                emptyText: 'Empty order list!<BR/><BR/><i>Start by ordering some items.</i>',
                itemTpl: [
                    '<table class="orderItemWrapper">',
                    '    <tr>',
                    '        <td class="orderItemImage" style="background-image: url(resources/images/{image});" />',
                    '        <td class="orderItemLabel">{name} ({count} x)</td>',
                    '        <td class="orderItemButtons1">',
                    '            <input action=\'decrease\' class="orderItemDecrease" type=\'button\' value=\'-\'>',
                    '            <input action=\'increase\' class="orderItemIncrease" type=\'button\' value=\'+\'>',
                    '        </td>',
                    '        <td class="orderItemButtons2">',
                    '            <input action=\'delete\' class="orderItemDelete" type=\'button\' value=\'X\'>',
                    '        </td>',
                    '    </tr>',
                    '</table>'
                ],
                store: 'OrderStore',
                grouped: true
            }
        ]
    }

});