/*
 * File: app/view/RegisterPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coffeeshop.view.RegisterPanel', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.Panel',
        'Ext.field.Email',
        'Ext.field.Password'
    ],

    config: {
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 60,
                title: 'Register',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'registerback',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        itemId: 'registerDoneButton',
                        ui: 'confirm',
                        width: 100,
                        text: 'Done'
                    }
                ]
            },
            {
                xtype: 'container',
                centered: true,
                height: '100%',
                maxWidth: 300,
                padding: 10,
                width: '100%',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'formpanel',
                        height: 210,
                        width: '100%',
                        defaults: {
                            margin: '5px',
                            labelWidth: '90px'
                        },
                        scrollable: 'horizontal',
                        layout: {
                            type: 'vbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'emailfield',
                                itemId: 'username',
                                label: 'Username:',
                                placeHolder: 'afsoun@me.com'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'password',
                                label: 'Password:',
                                placeHolder: 'password'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'confirm',
                                label: 'Confirm:',
                                placeHolder: 'retype password'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                height: 55,
                ui: 'light',
                layout: {
                    type: 'hbox',
                    pack: 'end'
                }
            }
        ]
    }

});