/*
 * File: app/view/WelcomePanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coffeeshop.view.WelcomePanel', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.form.Panel',
        'Ext.field.Email',
        'Ext.field.Password',
        'Ext.Button',
        'Ext.Img',
        'Ext.Label'
    ],

    config: {
        layout: {
            type: 'hbox',
            align: 'center',
            pack: 'center'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                height: 60,
                title: 'Welcome to our Coffeeshop'
            },
            {
                xtype: 'formpanel',
                height: '100%',
                width: 300,
                scrollable: false,
                layout: {
                    type: 'vbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 120,
                        items: [
                            {
                                xtype: 'emailfield',
                                itemId: 'username',
                                margin: 5,
                                label: 'Username:',
                                labelWidth: '90px',
                                placeHolder: 'afsoun@me.com'
                            },
                            {
                                xtype: 'passwordfield',
                                itemId: 'password',
                                margin: 5,
                                label: 'Password:',
                                labelWidth: '90px',
                                placeHolder: 'mypassword'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        height: 47,
                        itemId: 'loginButton',
                        ui: 'action-round',
                        width: 90,
                        text: 'Login'
                    }
                ]
            },
            {
                xtype: 'container',
                height: '100%',
                itemId: 'RegisterContainer',
                width: 300,
                layout: {
                    type: 'vbox',
                    align: 'center',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'container',
                        height: 120,
                        itemId: 'RegisterContainer1',
                        width: '100%',
                        layout: {
                            type: 'vbox',
                            align: 'center',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'container',
                                flex: 1,
                                itemId: 'WelcomeImageContainer',
                                width: '100%',
                                layout: {
                                    type: 'hbox',
                                    align: 'stretchmax',
                                    pack: 'end'
                                },
                                items: [
                                    {
                                        xtype: 'image',
                                        flex: 1,
                                        width: '',
                                        src: 'resources/images/welcome.jpg'
                                    },
                                    {
                                        xtype: 'image',
                                        flex: 1,
                                        height: '',
                                        width: '',
                                        src: 'resources/images/welcome1.jpg'
                                    }
                                ]
                            },
                            {
                                xtype: 'label',
                                html: 'New User?',
                                padding: 2
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        height: 41,
                        itemId: 'registerButton',
                        ui: 'action-round',
                        width: 110,
                        text: 'Register'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                height: 55,
                ui: 'light'
            }
        ]
    }

});