/*
 * File: app/controller/HomeController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Coffeeshop.controller.HomeController', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'HomePanel'
        ],

        control: {
            "button#logout": {
                tap: 'logoutButtonTapped'
            }
        }
    },

    logoutButtonTapped: function(button, e, eOpts) {
        var navigationView = button.up('#mainnavview');
        navigationView.pop();
        navigator.notification.alert("Logged out!", null, "Success", "Dismiss");
    }

});